spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    username: your_name
    password: your_password
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender:
      email: your_name@yandex.ru
      text: no-reply